meta_product_name: "Wonderrkid"
meta_title: "Wonderrkid - Dream big"
meta_description: "Connecting athletes and scouts all over the world."
meta_image: "cover.png" # should exist in `app/assets/images/`
